events {
    worker_connections 1024;
}

http {
    upstream app_backend {
        server application:3000;
    }
    
    server {
        listen 80;
        
        location / {
            proxy_pass http://app_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        
        location /health {
            proxy_pass http://app_backend/health;
        }
        
        location /db-test {
            proxy_pass http://app_backend/db-test;
        }
    }
}
